### ISSUE TITLE
pooof - where did your CLI primer go??

### ISSUE THREAD

**Issue by ffd8** [nbriz/netart.rocks#1]
heeey @nbriz was just updating [this guide](https://ffd8.github.io/cli-for-artists-and-designers/), checking links, and found that your [CLI Primer](http://netart.rocks/notes/commandline) is now 404... checked the repo here and don't find a `/notes/commandline` anymore... perhaps moved names/locations or didn't make the updates cut?? it was really helpful, soooo **`+1`** for reinstating it..

**Comment by nbriz** [comment]
oh dang! good catch! i move these notes around a lot, think that might have vanished in a recent reorganization. i'll try to find it && get it back up!

**Comment by nbriz** [comment]
@ffd8 found it: https://netizen.org/workshops/the-command-line/ :)
